pub mod line;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Config {
    pub line: Option<line::Config>,
}

pub trait Oauth {
    fn name(&self) -> &'static str;
    // A unique alphanumeric string used to prevent cross-site request forgery. This value should be randomly-generated by your application.
    // Cannot be a URL-encoded string.
    fn authorization_url(&self, state: &String, nonce: &String) -> String;
}
