CREATE TABLE forum_categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  color VARCHAR(16) NOT NULL,
  icon VARCHAR(16) NOT NULL,
  description VARCHAR(500),
  parent_id INT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE forum_topics (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  user_id INT NOT NULL,
  category_id INT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE forum_posts (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  user_id INT NOT NULL,
  post_id INT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE forum_tags (
  id SERIAL PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  background_color VARCHAR(16) NOT NULL,
  text_color VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX idx_forum_tags_name ON forum_tags (name);

CREATE TABLE forum_topics_tags (
  id SERIAL PRIMARY KEY,
  topic_id INT NOT NULL,
  tag_id INT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX idx_forum_topics_tags ON forum_topics_tags (topic_id, tag_id);
