CREATE TABLE settings (
  id BIGSERIAL PRIMARY KEY,
  KEY VARCHAR(255) NOT NULL,
  salt BYTEA,
  value BYTEA NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX idx_settings_key ON settings (KEY);
