CREATE TABLE logs (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  ip VARCHAR(128) NOT NULL,
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
